// Extra brands for the demo catalogue: name, symbol, sector, rarity, logo slug, domain, dark mark, wide wordmark.
// Sectors: 1 Logistics, 2 Beverages, 3 Mobility, 4 Screens, 5 Energy, 6 Food, 7 Retail, 8 Finance, 9 Fashion, 10 Home, 11 Travel, 12 Industry.
module.exports = [
  ["Walmart", "WMT", 7, 0.5, "walmart", "walmart.com", 0, 1],
  ["Target", "TGT", 7, 0.9, "target", "target.com", 0, 0],
  ["Visa", "V", 8, 0.45, "visa", "visa.com", 0, 1],
  ["Mastercard", "MA", 8, 0.5, "mastercard", "mastercard.com", 0, 0],
  ["American Express", "AXP", 8, 1.6, "amex", "americanexpress.com", 0, 0],
  ["Google", "GOOGL", 4, 0.5, "google", "google.com", 0, 1],
  ["Meta", "META", 4, 1.2, "meta", "meta.com", 0, 1],
  ["Disney", "DIS", 4, 1.3, "disney", "disney.com", 1, 1],
  ["Home Depot", "HD", 7, 1.1, "homedepot", "homedepot.com", 0, 0],
  ["Chevron", "CVX", 5, 0.9, "chevron", "chevron.com", 0, 0],
  ["Burger King", "QSR", 6, 0.7, "burgerking", "bk.com", 0, 0],
  ["KFC", "YUM", 6, 0.7, "kfc", "kfc.com", 0, 0],
  ["Chipotle", "CMG", 6, 1.4, "chipotle", "chipotle.com", 0, 1],
  ["Intel", "INTC", 4, 1.8, "intel", "intel.com", 0, 1],
  ["Nvidia", "NVDA", 4, 2.4, "nvidia", "nvidia.com", 1, 1],
  ["Spotify", "SPOT", 4, 1.1, "spotify", "spotify.com", 1, 1],
  ["Airbnb", "ABNB", 11, 1.5, "airbnb", "airbnb.com", 0, 0],
  ["Lyft", "LYFT", 3, 1.0, "lyft", "lyft.com", 0, 1],
  ["DoorDash", "DASH", 6, 0.9, "doordash", "doordash.com", 0, 1],
  ["IBM", "IBM", 4, 1.9, "ibm", "ibm.com", 0, 1],
  ["Adidas", "ADS", 9, 0.8, "adidas", "adidas.com", 1, 0],
  ["Puma", "PUM", 9, 1.2, "puma", "puma.com", 1, 1],
  ["H&M", "HM-B", 9, 0.7, "hm", "hm.com", 0, 1],
  ["Volkswagen", "VOW3", 3, 0.55, "volkswagen", "vw.com", 0, 0],
  ["BMW", "BMW", 3, 0.7, "bmw", "bmw.com", 1, 0],
  ["Mercedes-Benz", "MBG", 3, 0.6, "mercedes", "mercedes-benz.com", 1, 0],
  ["Audi", "VOW3", 3, 0.8, "audi", "audi.com", 1, 1],
  ["Renault", "RNO", 3, 0.85, "renault", "renault.com", 1, 0],
  ["Ferrari", "RACE", 3, 6.5, "ferrari", "ferrari.com", 0, 0],
  ["Siemens", "SIE", 12, 1.6, "siemens", "siemens.com", 0, 1],
  ["Philips", "PHIA", 10, 1.3, "philips", "philips.com", 0, 1],
  ["L'Oréal", "OR", 9, 1.1, "loreal", "loreal.com", 1, 1],
  ["Louis Vuitton", "MC", 9, 2.8, "louisvuitton", "louisvuitton.com", 1, 1],
  ["Gucci", "KER", 9, 3.0, "gucci", "gucci.com", 1, 1],
  ["Heineken", "HEIA", 2, 0.8, "heineken", "heineken.com", 0, 1],
  ["Carrefour", "CA", 7, 0.75, "carrefour", "carrefour.com", 0, 1],
  ["Tesco", "TSCO", 7, 0.8, "tesco", "tesco.com", 0, 1],
  ["Vodafone", "VOD", 4, 0.9, "vodafone", "vodafone.com", 0, 0],
  ["Orange", "ORA", 4, 0.85, "orange", "orange.com", 0, 0],
  ["Deutsche Telekom", "DTE", 4, 0.9, "telekom", "telekom.com", 0, 1],
  ["Lufthansa", "LHA", 11, 2.2, "lufthansa", "lufthansa.com", 1, 1],
  ["Ryanair", "RYAAY", 11, 1.9, "ryanair", "ryanair.com", 0, 1],
  ["Airbus", "AIR", 12, 3.4, "airbus", "airbus.com", 0, 1],
  ["SAP", "SAP", 4, 1.5, "sap", "sap.com", 0, 1],
  ["Zalando", "ZAL", 7, 1.1, "zalando", "zalando.com", 0, 1],
  ["Allianz", "ALV", 8, 1.3, "allianz", "allianz.com", 0, 1],
  ["AXA", "CS", 8, 1.2, "axa", "axa.com", 0, 0],
  ["HSBC", "HSBA", 8, 1.2, "hsbc", "hsbc.com", 1, 1],
  ["Santander", "SAN", 8, 1.0, "santander", "santander.com", 0, 1],
  ["Hyundai", "005380", 3, 0.7, "hyundai", "hyundai.com", 0, 1],
  ["Kia", "000270", 3, 0.75, "kia", "kia.com", 1, 1],
  ["Nintendo", "NTDOY", 4, 1.7, "nintendo", "nintendo.com", 0, 1],
  ["LG", "066570", 4, 1.0, "lg", "lg.com", 0, 1],
  ["Panasonic", "6752", 4, 1.2, "panasonic", "panasonic.com", 0, 1],
  ["Uniqlo", "9983", 9, 0.9, "uniqlo", "uniqlo.com", 0, 1],
  ["Canon", "CAJ", 4, 1.4, "canon", "canon.com", 0, 1],
  ["Xiaomi", "1810", 4, 1.1, "xiaomi", "mi.com", 0, 0],
  ["Shopify", "SHOP", 4, 2.1, "shopify", "shopify.com", 1, 1],
  ["Lululemon", "LULU", 9, 1.6, "lululemon", "lululemon.com", 0, 0],
  ["Delta", "DAL", 11, 2.0, "delta", "delta.com", 0, 1],
  ["American Airlines", "AAL", 11, 2.0, "americanairlines", "aa.com", 0, 1],
  ["Procter & Gamble", "PG", 10, 0.7, "pg", "pg.com", 0, 1],
  ["Kellogg's", "K", 6, 0.9, "kelloggs", "kelloggs.com", 0, 1],
  ["Chevrolet", "GM", 3, 0.65, "chevrolet", "chevrolet.com", 0, 1],
  ["Jeep", "STLA", 3, 0.9, "jeep", "jeep.com", 1, 1],
  ["Caterpillar", "CAT", 12, 2.6, "caterpillar", "caterpillar.com", 1, 1],
  ["John Deere", "DE", 12, 2.4, "johndeere", "deere.com", 0, 1],
  ["Boeing", "BA", 12, 4.8, "boeing", "boeing.com", 0, 1],
  ["Dell", "DELL", 4, 1.3, "dell", "dell.com", 0, 0],
  ["HP", "HPQ", 4, 1.2, "hp", "hp.com", 0, 0],
  ["Cisco", "CSCO", 4, 2.2, "cisco", "cisco.com", 0, 1],
  ["Oracle", "ORCL", 4, 2.3, "oracle", "oracle.com", 0, 1],
  ["Adobe", "ADBE", 4, 2.0, "adobe", "adobe.com", 0, 1],
  ["Coinbase", "COIN", 8, 2.5, "coinbase", "coinbase.com", 0, 1],
  ["Bank of America", "BAC", 8, 0.9, "bankofamerica", "bankofamerica.com", 0, 1],
  ["Chase", "JPM", 8, 0.9, "chase", "chase.com", 0, 1],
  ["Wells Fargo", "WFC", 8, 1.0, "wellsfargo", "wellsfargo.com", 0, 1],
  ["CVS", "CVS", 7, 0.8, "cvs", "cvs.com", 0, 1],
  ["Walgreens", "WBA", 7, 0.8, "walgreens", "walgreens.com", 0, 1],
  ["Lowe's", "LOW", 7, 1.0, "lowes", "lowes.com", 0, 1],
  ["Wendy's", "WEN", 6, 1.0, "wendys", "wendys.com", 0, 1],
  ["7-Eleven", "3382", 7, 0.6, "7eleven", "7-eleven.com", 0, 0],
  ["Ericsson", "ERIC", 4, 2.0, "ericsson", "ericsson.com", 0, 1],
  ["Nokia", "NOK", 4, 1.6, "nokia", "nokia.com", 0, 1],
  ["BIC", "BB", 10, 0.9, "bic", "bic.com", 0, 1],
  ["Repsol", "REP", 5, 1.0, "repsol", "repsol.com", 0, 1],
  ["Air France", "AF", 11, 2.1, "airfrance", "airfrance.com", 1, 1],
  ["easyJet", "EZJ", 11, 1.8, "easyjet", "easyjet.com", 0, 1],
  ["ING", "INGA", 8, 1.2, "ing", "ing.com", 0, 1],
  ["BNP Paribas", "BNP", 8, 1.2, "bnp", "bnpparibas.com", 0, 1],
  ["Deutsche Bank", "DBK", 8, 1.5, "deutschebank", "db.com", 0, 0],
  ["Barclays", "BARC", 8, 1.3, "barclays", "barclays.com", 0, 1],
  ["Peugeot", "STLA", 3, 0.8, "peugeot", "peugeot.com", 1, 0],
  ["Fiat", "STLA", 3, 0.8, "fiat", "fiat.com", 0, 0],
  ["Continental", "CON", 3, 1.5, "continental", "continental.com", 1, 1],
  ["Nissan", "7201", 3, 0.75, "nissan", "nissan-global.com", 1, 0],
  ["Suzuki", "7269", 3, 0.8, "suzuki", "globalsuzuki.com", 0, 1],
  ["Harley-Davidson", "HOG", 3, 2.3, "harley", "harley-davidson.com", 1, 1],
  ["Tencent", "0700", 4, 1.6, "tencent", "tencent.com", 0, 1],
  ["Toshiba", "6502", 4, 1.5, "toshiba", "toshiba.com", 0, 1],
  ["Honda", "HMC", 3, 0.7, "honda", "honda.com", 1, 0],
  ["Danone", "BN", 6, 0.9, "danone", "danone.com", 0, 1],
  ["Michelin", "ML", 3, 1.3, "michelin", "michelin.com", 0, 1],
  ["Alibaba", "BABA", 4, 1.5, "alibaba", "alibaba.com", 0, 1],
  ["BYD", "1211", 3, 1.2, "byd", "byd.com", 0, 1],
  ["Robinhood", "HOOD", 8, 3.6, "robinhood", "robinhood.com", 0, 1],
  ["Volvo", "VOLCAR-B", 3, 1.1, "volvo", "volvocars.com", 1, 0],
  ["Porsche", "P911", 3, 3.8, "porsche", "porsche.com", 1, 0],
  ["Marriott", "MAR", 11, 1.6, "marriott", "marriott.com", 1, 1],
  ["Colgate", "CL", 10, 0.8, "colgate", "colgate.com", 0, 1],
  ["Heinz", "KHC", 6, 0.8, "heinz", "kraftheinzcompany.com", 0, 1],
  ["Budweiser", "BUD", 2, 0.9, "budweiser", "budweiser.com", 0, 1],
  ["UBS", "UBS", 8, 1.9, "ubs", "ubs.com", 0, 1],
  ["Hilton", "HLT", 11, 1.7, "hilton", "hilton.com", 1, 1],
];
